name: transly
description: "Translation app with OCR and PDF support"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # OCR and PDF
  google_mlkit_text_recognition: ^0.15.0
  read_pdf_text: ^0.3.0

  # File handling
  file_picker: ^10.1.2
  path: ^1.9.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5


  # Translation
  translator: ^1.0.3+1

  # UI
  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user.png
    - assets/app.png
